[config]
default_to_workspace = false

[tasks.fmt]
script = ['''
#!/usr/bin/env bash -eux
cargo fmt --all
''']

[tasks.lint]
env = { RUSTFLAGS = "-D warnings" }
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--all-features"]

[tasks.build]
env = { RUSTFLAGS = "-D warnings" }
command = "cargo"
args = ["build", "--workspace", "--all-targets", "--all-features"]

[tasks.test]
command = "cargo"
args = ["test", "--workspace", "--all-targets", "--all-features"]

[tasks.doc]
run_task = { name = ["_doc-clean", "_doc"] }
[tasks._doc-clean]
command = "cargo"
args = ["clean", "--doc"]
[tasks._doc]
command = "cargo"
args = ["doc", "--no-deps", "--all-features"]
