[config]
default_to_workspace = false

[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.lint]
env = { RUSTFLAGS = "-D warnings" }
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--all-features"]

[tasks.build]
env = { RUSTFLAGS = "-D warnings" }
command = "cargo"
args = ["build", "--workspace", "--all-targets", "--all-features"]
