[package]
name = "apllodb-immutable-schema-engine-infra"
version = "0.1.0"
authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apllodb-immutable-schema-engine-domain = { path = "../apllodb-immutable-schema-engine-domain" }
apllodb-immutable-schema-engine-application = { path = "../apllodb-immutable-schema-engine-application" }
apllodb-immutable-schema-engine-interface-adapter = { path = "../apllodb-immutable-schema-engine-interface-adapter" }

apllodb-storage-engine-interface = { path = "../apllodb-storage-engine-interface" }

apllodb-shared-components = { path = "../apllodb-shared-components" }

chrono = "0.4"

env_logger = "0.7"
log = "0.4"

rusqlite = { version = "0.23", features = ["bundled"] }
libsqlite3-sys = "0.18"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[dev-dependencies]
uuid = { version = "0.8", features = ["v4"] }
version-sync = "0.9"
