[package]
authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
edition = "2018"
name = "apllodb-immutable-schema-engine-infra"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apllodb-immutable-schema-engine-application = {path = "../apllodb-immutable-schema-engine-application"}
apllodb-immutable-schema-engine-domain = {path = "../apllodb-immutable-schema-engine-domain"}

apllodb-storage-engine-interface = {path = "../apllodb-storage-engine-interface"}

apllodb-shared-components = {path = "../apllodb-shared-components"}

# Only SqliteTx uses this to deserialize ActiveVersion from SQLite's sqlite_master table.
apllodb-sql-parser = {path = "../apllodb-sql-parser"}

chrono = "0.4"

derive-new = "0.5"

env_logger = "0.8"
log = "0.4"

libsqlite3-sys = "0.20"
rusqlite = {version = "0.24", features = ["bundled"]}

serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.8"

[dev-dependencies]
pretty_assertions = "0.6"
rand = "0.8"
uuid = {version = "0.8", features = ["v4"]}
version-sync = "0.9"
