[package]
authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
categories = ["database", "database-implementations"]
description = "apllodb's storage engine interface."
edition = "2018"
keywords = ["apllodb"]
license = "(TBD)"
name = "apllodb-storage-engine-interface"
readme = "README.md"
repository = "https://github.com/darwin-education/apllodb"
version = "0.1.0"

[dependencies]
apllodb-shared-components = {path = "../apllodb-shared-components"}

serde = {version = "1.0", features = ["derive"]}
tarpc = {version = "0.24", features = ["full"]}

[dev-dependencies]
version-sync = "0.9"
