[package]
name = "apllodb-immutable-schema-engine"
version = "0.1.0"
authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apllodb-immutable-schema-engine-infra = { path = "../apllodb-immutable-schema-engine-infra" }
apllodb-shared-components = { path = "../apllodb-shared-components" }
apllodb-storage-engine-interface = { path = "../apllodb-storage-engine-interface" }
