[package]
name = "apllodb-immutable-schema-engine"
version = "0.1.0"
authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
edition = "2018"
description = "apllodb's original storage engine that provides Immutable Schema feature."
license = "(TBD)"
readme = "README.md"
keywords = ["apllodb"]
categories = ["database", "database-implementations"]
repository = "https://github.com/darwin-education/apllodb"

[dependencies]
apllodb-shared-components = { path = "../apllodb-shared-components" }
apllodb-storage-manager-interface = { path = "../apllodb-storage-manager-interface" }
chrono = "0.4"

libsqlite3-sys = "0.18"
rusqlite = "0.23"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[dev-dependencies]
version-sync = "0.9"
