name: fuzzing_test

on:
  schedule:
    - cron:  '30 6 * * *'  # UTC 6:30

jobs:
  run_fuzz:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apllodb-server/fuzz/
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          set -xe
          sudo apt update -y
          sudo apt install -y libsqlite3-dev

      - name: rustup override set `cat rust-toolchain`
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      # https://github.com/actions/cache/blob/master/examples.md#using-multiple-systems-and-npm-config
      - name: Get running rustc --version
        id: rustc_version
        run: |
          echo "::set-output name=version::$(rustc --version)"

      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo install cargo-fuzz

      - name: Download previous corpus
        uses: actions/download-artifact@v2

      - run: cargo fuzz run random_string_with_session_without_db -- -max_total_time=3600  # in seconds

      - name: Archive corpus
        uses: actions/upload-artifact@v2
        with:
          name: corpus
          path: |
            apllodb-server/fuzz/corpus
          if-no-files-found: error

  slack-notify:
    if: always()
    needs:
      - run_fuzz
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_APLLODB_CI_WEBHOOK_URL }}
