name: fuzzing_test

on:
  schedule:
    - cron:  '30 6 * * *'  # UTC 6:30

jobs:
  run_fuzz:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apllodb-server/fuzz/
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.rust }}
        if: ${{ ! matrix.rust-free }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true

      - name: Cache cargo registry
        if: ${{ ! matrix.rust-free }}
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: cargo install cargo-fuzz

      - name: Download corpus from previous successful workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: fuzzing-test.yml
          path: apllodb-server/fuzz/

      - run: cargo fuzz run random_string_with_session_without_db -- -max_total_time=3600  # in seconds

      - name: Archive corpus
        uses: actions/upload-artifact@v2
        with:
          name: corpus
          path: apllodb-server/fuzz/corpus
          if-no-files-found: error

  slack-notify:
    if: failure()
    needs:
      - run_fuzz
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_APLLODB_CI_WEBHOOK_URL }}
