name: pull_request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_correct:
    runs-on: ubuntu-latest
    env:
      # PERSONAL_TOKEN_TO_TRIGGER_ANOTHER_WORKFLOW:
      #   Instead of GITHUB_TOKEN (which cannot trigger another workflow: https://docs.github.com/ja/free-pro-team@latest/actions/reference/authentication-in-a-workflow#%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%83%AD%E3%83%BC%E5%86%85%E3%81%A7%E3%81%AEgithub_token%E3%81%AE%E5%88%A9%E7%94%A8),
      #   issue your personal token and set it to secret.
      REPO: https://${{github.actor}}:${{secrets.PERSONAL_TOKEN_TO_TRIGGER_ANOTHER_WORKFLOW}}@github.com/${{github.repository}}.git
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          persist-credentials: false

      - name: rustup override set `cat rust-toolchain`
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt

      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: commit formatted sources and push
        run: |
          git config --global user.email "workflow@example.com"
          git config --global user.name "workflow user"
          git add .
          if git commit -m '(auto commit) cargo fmt' ; then
            git push ${REPO} HEAD:${{github.event.pull_request.head.ref}}
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: checks if any `todo!()` or `unimplemented!()` is used (to prevent easy server crash)
        run: |
          git ls-files |grep -E '.rs$' |(! xargs grep 'unimplemented!')
          git ls-files |grep -E '.rs$' |(! xargs grep 'todo!')

      - name: rustup override set `cat rust-toolchain`
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: clippy

      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    env:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    strategy:
        matrix:
          rust:
            - ""      # `rust-toolchain`
            - 1.48.0  # MSRV
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-apllodb-dep

      # https://github.com/actions-rs/meta/blob/master/recipes/matrix.md
      - name: rustup override set {{ matrix.rust }}
        if: matrix.rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: rustup override set `cat rust-toolchain`
        if: matrix.rust == ''
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo build
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -D warnings
        with:
          command: build
          args: --all-features --all-targets

      - name: checks if CLI client runs without crash
        run: |
          echo 'CREATE DATABASE abc' | ./target/debug/apllodb-cli
          rm *.sqlite3*

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: checks if tests clean .sqlite3* files (use SqliteDatabaseCleaner if fails)
        run: |
           [ $(find . -name '*.sqlite3*' |wc -l) = '0' ] || ( find . -name '*.sqlite3*' ; false )

  check_rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
                
      - name: rustup override set `cat rust-toolchain`
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
        
      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: cargo clean --doc
        uses: actions-rs/cargo@v1
        with:
          command: clean
          args: --doc
      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --all-features
          
      # TODO comment-in
      # - run: cargo install cargo-deadlinks
      # - run: cargo deadlinks

  slack-notify:
    if: always()
    needs:
      - lint
      - test
      - check_rustdoc
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_APLLODB_CI_WEBHOOK_URL }}
